### ISSUE TITLE
inject configuration into service

### ISSUE THREAD

**Issue by 2efPer** [sadhen/spring-booted-scala#1]
如果我要完成如下的功能：

> @Service
class WorldService @Autowired()(private val config: MyConfiguration){
  def getCountry: String = {
    "中国"+ config.someArgs
  }
}   

其中MyConfiguration是用来读取application.properties中的配置。在Java中的代码应该如下：  

> @Component
public class MyConfiguration {
    private String cvmodelpath;
//... getter& setter
}  

请问MyConfiguration 如何改写成scala的形式？

**Comment by sadhen** [comment]
一般用Java能写出来的，Scala都能写出来，你可以思考一下。除了这种方式，还可以使用 https://github.com/zhongl/config-annotation 。

另外，建议了解一下Github Flavored Markdown的具体用法。
